</td>
 <td width="170">
  <center> 
  <? include("googleads.inc"); ?>
  </center>
 </td>
  </tr>
</table>


<p align="center"><br>
<img height="2" src="line.gif" width="730" border="0"><br>
<strong><font color="#000000" face="Comic Sans MS">TheDemoSite.co.uk</font></strong> is a
MySQL database and PHP code example site hosted at: <br><b>Seiretto </b>
<strong><a href="http://www.seiretto.com/">UK web site hosting</a></strong> - 
<strong><a href="http://www.seiretto.com/web_hosting/php_hosting.php">PHP hosting</a></strong>
Copyright © 1996-2006 Seiretto.&nbsp; All rights reserved.<img height="2" src="line.gif"
width="730" border="0"></p>
<p align="center"><a href="http://www.uk-web-hosting-directory.org">Reasons WHY you should use UK web hosting for your UK business</a>
</p>
</body>
</html>
