<html>

<head>
<title>Example PHP code and online MySQL database (cut-and-paste examples). The example is
a username and password protected site example.</title>
<meta name="keywords"
content="example PHP code,demo username and password example,PHP scripts,PHP hosting, PHP database,database,databases,mysql,mysql  database,active server pages, web hosting">
<meta name="Revisit-after" content="56 days">
<meta name="Distribution" content="Global">
<meta name="Copyright" content="Copyright © 1996-2001 Seiretto.com">
<meta name="description"
content="Example PHP code and a MySQL database (cut-and-paste examples). The example is a username and password protected site  example.">
<meta NAME="ROBOTS" CONTENT="ALL">
<link rel="stylesheet" type="text/css" href="tds.css">
</head>

<body BACKGROUND="DiscoverBack.gif"
style="
    SCROLLBAR-ARROW-COLOR: #BBCCFF; 
    SCROLLBAR-TRACK-COLOR: #C9DAF7; 
    SCROLLBAR-FACE-COLOR:  #002163;"
TOPMARGIN="0" LEFTMARGIN="15" MARGINWIDTH="0" MARGINHEIGHT="0">
<div align="center"><center>

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="100%"><p align="center"><img height="2" src="line.gif" width="99%" border="0"
    alt="PHP code examples with database connectivity"></td>
  </tr>
  <tr>
    <td><p align="center">
<a href="http://asp.thedemosite.co.uk"><font face="Comic Sans MS"
color="#ff0000"><strong><big>A</font><font face="Comic Sans MS" color="#47b855">S</font><font
face="Comic Sans MS" color="#0000ff">P</font><font face="Comic Sans MS" color="#000000">.TheDemoSite.co.uk</font></a>
</big></strong><font
    color="#000000"><small><small><script language="JavaScript"><!--
document.write("Just examples of <b>ASP</b> code, linking to your <b>Microsoft Access</b> database and JavaScript.");
// --></script></small></small></font></td>
  </tr>
  <tr>
    <td width="100%"><img height="2" src="line.gif" width="99%" border="0"
    alt="PHP code examples with database connectivity"><div align="center"><center><table
    border="0" width="98%" cellspacing="0" cellpadding="0">
      <tr>
        <td width="9%"><font face="Comic Sans MS"><strong><big>&nbsp;PHP.TheDemoSite.co.uk</big></strong></font></td>
        <td><p align="center"><small>Just examples of <b>PHP</b> code, linking to your <b>MySQL</b>
        database and JavaScript.<br>
        <a href="index.php">1. Home</a> | <a href="thedatabase.php">2. The Database</a> | <a
        href="addauser.php">3. Add a User</a> | <a href="login.php">4. Login</a> | <a
        href="getyourowndbonline.php">5. Get your db online</a></small></td>
      </tr>
    </table>
    </center></div></td>
  </tr>
  <tr>
    <td width="100%"><p align="center"><img height="2" src="line.gif" width="99%" border="0"
    alt="PHP code examples with database connectivity"><br>
    </td>
  </tr>
</table>
</center></div>
<p align="center"><a href="http://thedemosite.co.uk/phpformmailer/"><strong>PHP Form
Mailer - phpFormMailer </strong>(easy to use and more secure than many cgi form mailers</a>)</p>
<? include("hostscripts-12870.inc");?>
</table>

<table border="0" width="100%">
  <tr>
    <td>
