<div align="center"><center>

<table border="0" cellspacing="0" cellpadding="0" width="800">
  <tr>
    <td width="140"><strong><h2><a href="http://www.seiretto.com/web_hosting/php_hosting.php">PHP
    hosting</a></h2>
    </strong></td>
    <td align="center" width="400"><table cellSpacing="0" cellPadding="0" border="0">
      <tr>
        <td align="center"><table cellSpacing="0" cellPadding="0" bgColor="#DFDFDF" border="0">
          <tr>
            <td><p align="center"><small><small>PHP MySQL auto members area: </small></small><a
            href="http://www.dwalker.co.uk/phpautomembersarea/"><small>phpAutoMembersArea (phpAMA)</small></a>
            </td>
          </tr>
          <tr>
            <td><small><p align="center"><small><small>PHP Job scheduler: <a
            href="http://www.phpjobscheduler.co.uk/">phpJobScheduler</a></small></small></small></td>
          </tr>
        </table>
        </td>
      </tr>
    </table>
    </td>
    <td width="260"><?php include("download.php"); ?></td>
  </tr>
</table>
</center></div>